=== simransingh27/Algorithms-Multithreading-Practice/Practice/src/test/user-list.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT users (user)+>
<!ELEMENT user (forename?, surname?, email)>
<!ELEMENT forename (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== simransingh27/Algorithms-Multithreading-Practice/Practice/src/test/user-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE users SYSTEM "user-list.dtd">
<users>
    <user>
        <forename>Joe</forename>
        <surname>Bloggs</surname>
        <email>j.bloggs@sample.co.uk</email>
    </user>
    <user>
        <forename>Winston</forename>
        <surname>Smith</surname>
        <email>w.smith@airstripOne.gov</email>
    </user>
    <user>
        <forename>John</forename>
        <surname>Smith</surname>
        <email>john.smith@somewhere.com</email>
    </user>
    <user>
        <forename>Thorin</forename>
        <surname>Oakenshield</surname>
        <email>chief@dwarvesreunited.com</email>
    </user>
    <user>
        <forename>Bugs</forename>
        <surname>Bunny</surname>
        <email>bugs.bunny@looney.com</email>
    </user>
    <user>
        <forename>Anna</forename>
        <surname>Andrews</surname>
        <email>a.andrews@andrews.co.uk</email>
    </user>
    <user>
        <forename>Mickey</forename>
        <surname>Mouse</surname>
        <email>mickey@disney.com</email>
    </user>
    <user>
        <forename>Ruth</forename>
        <surname>Rendell</surname>
        <email>ruthrendell@authors.com</email>
    </user>
    <user>
        <forename>Donald</forename>
        <surname>Duck</surname>
        <email>duck@disney.com</email>
    </user>
    <user>
        <email>a.nonymous@mailinator.com</email>
    </user>
    <user>
        <forename>
            Han
        </forename>
        <surname>
            Solo
        </surname>
        <email>pilot@milleniumfalcon.co.sw</email>
    </user>
    <user>
        <forename>Bilbo</forename>
        <surname>Baggins</surname>
        <email>bilbo.baggins@theshire.co.nz</email>
    </user>
    <user>
        <forename>Arthur</forename>
        <surname>Pendragon</surname>
        <email>king.arthur@camelot.co.uk</email>
    </user>
    <user>
        <forename>Sherlock</forename>
        <surname>Holmes</surname>
        <email>detective@bakerstreet.gov.uk</email>
    </user>
    <user>
        <forename>Robin</forename>
        <surname>Hood</surname>
        <email>robin@loxley.co.uk</email>
    </user>
    <user>
        <email>son.of.darth@tatooine.com</email>
    </user>
    <user>
        <forename>William</forename>
        <surname>Shakespeare</surname>
        <email>bill@stratford.co.uk</email>
    </user>
    <user>
        <forename>Moby</forename>
        <surname>Dick</surname>
        <email>whale@melville.com</email>
    </user>
    <user>
        <forename>Endeavour</forename>
        <surname>Morse</surname>
        <email>morse@thamesvalleypolice.co.uk</email>
    </user>
    <user>
        <forename>Oliver</forename>
        <surname>Twist</surname>
        <email>oliver@workhouse.org</email>
    </user>
</users>
